name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Get version from pom.xml
        id: get-version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Show GITHUB_OUTPUT
        # IMAGE_NAME: nombre del repositorio
        # VERSION: versión sacado del fichero POM
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          VERSION=${{ steps.get-version.outputs.version }}
          echo $IMAGE_NAME:$VERSION

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io #GitHub Container Registry
          username: ${{ github.actor }}  # Utiliza el contexto para obtener el nombre del autor
          # 1º Creación del Token de Acceso Personal
          #    Cuenta de GitHub >> Developer settings >> Personal access tokens >> Tokens >> Generate new token
          #    write:packages & read:packages delete:packages & repo
          # 2º Configuración de Secrets en GitHub
          #    repositorio en GitHub >> settings >> secrets and variables >> actions >> new repository secret
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and Tag Docker image
        # docker build se construye la imagen de docker a partir del fichero Dockerfile
        # docker tag: se etiqueta la imagen con la versión actual y se establece que es la última
        run: |
          docker build -t $IMAGE_NAME:$VERSION .
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
#      - name: Build Docker image
#        run: |
#          docker build -t ${{ github.repository }}:${{ steps.get-version.outputs.version }} .
#          docker tag ${{ github.repository }}:${{ steps.get-version.outputs.version }} ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }}
#          docker tag ${{ github.repository }}:${{ steps.get-version.outputs.version }} ghcr.io/${{ github.repository }}:latest
#
#      - name: Push Docker image to GitHub Container Registry
#        run: |
#          docker push ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }}
#          docker push ghcr.io/${{ github.repository }}:latest
#
#      - name: Solicita a Render nuevo despliegue
#        run: curl https://api.render.com/deploy/${{ secrets.RENDER_KEY_DEPLOY_HOOK }}
