name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Get version from pom.xml
        id: get-version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Show GITHUB_OUTPUT
        run: echo ${{ steps.get-version.outputs.version }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CD_TOKEN }}

#      - name: Build Docker image
#        run: |
#          docker build -t ${{ github.repository }}:${{ steps.get-version.outputs.version }} .
#          docker tag ${{ github.repository }}:${{ steps.get-version.outputs.version }} ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }}
#          docker tag ${{ github.repository }}:${{ steps.get-version.outputs.version }} ghcr.io/${{ github.repository }}:latest
#
#      - name: Push Docker image to GitHub Container Registry
#        run: |
#          docker push ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }}
#          docker push ghcr.io/${{ github.repository }}:latest
#
#      - name: Solicita a Render nuevo despliegue
#        run: curl https://api.render.com/deploy/${{ secrets.RENDER_KEY_DEPLOY_HOOK }}
